name: Build and draft release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: 'Build and draft release'
    runs-on: ubuntu-22.04
    container: explyt/tsa-env:v1.1.3

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: 'Add git path to trusted'
        run: |
          git config --global --add safe.directory ${GITHUB_WORKSPACE}

      - name: Set SHA output
        id: sha
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "sha_full=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: 'Assemble'
        run: ./gradlew clean :tsa-cli:shadowJar

      - name: 'Create draft release'
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          prerelease: true
          name: Build for ${{ steps.sha.outputs.sha_short }}
          body: Automated draft release for commit ${{ steps.sha.outputs.sha_full }}
          files: |
            **/build/libs/tsa-cli.jar
